/*
  # Add Remaining Vocabulary for Topics

  This migration adds complete vocabulary for:
  - School and Classroom (50 words)
  - Numbers and Time (70+ words)
  - Colors and Shapes (50 words)
  - Daily Activities (50 words)
*/

-- B. SCHOOL AND CLASSROOM (50 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'school-and-classroom') t
CROSS JOIN (VALUES
  ('teacher', '/ˈtiːtʃə(r)/', 'guru', 'The teacher explains the lesson.', 'noun', ARRAY['people']::text[], 1),
  ('student', '/ˈstjuːdnt/', 'murid', 'The students are studying hard.', 'noun', ARRAY['people']::text[], 1),
  ('principal', '/ˈprɪnsəpl/', 'kepala sekolah', 'The principal is very kind.', 'noun', ARRAY['people']::text[], 2),
  ('janitor', '/ˈdʒænɪtə(r)/', 'penjaga sekolah', 'The janitor cleans the school.', 'noun', ARRAY['people']::text[], 2),
  ('classroom', '/ˈklɑːsruːm/', 'ruang kelas', 'Our classroom is clean and bright.', 'noun', ARRAY['place']::text[], 1),
  ('library', '/ˈlaɪbrəri/', 'perpustakaan', 'I borrowed books from the library.', 'noun', ARRAY['place']::text[], 1),
  ('laboratory', '/ləˈbɒrətri/', 'laboratorium', 'We do science experiments in the laboratory.', 'noun', ARRAY['place']::text[], 2),
  ('canteen', '/kænˈtiːn/', 'kantin', 'We eat lunch in the canteen.', 'noun', ARRAY['place']::text[], 1),
  ('book', '/bʊk/', 'buku', 'I read an interesting book.', 'noun', ARRAY['object']::text[], 1),
  ('notebook', '/ˈnəʊtbʊk/', 'buku catatan', 'Write notes in your notebook.', 'noun', ARRAY['object']::text[], 1),
  ('dictionary', '/ˈdɪkʃənri/', 'kamus', 'Use a dictionary to find word meanings.', 'noun', ARRAY['object']::text[], 2),
  ('pen', '/pen/', 'pena', 'I write with a blue pen.', 'noun', ARRAY['object']::text[], 1),
  ('pencil', '/ˈpensl/', 'pensil', 'Please lend me a pencil.', 'noun', ARRAY['object']::text[], 1),
  ('sharpener', '/ˈʃɑːpnə(r)/', 'serutan', 'I need a pencil sharpener.', 'noun', ARRAY['object']::text[], 1),
  ('eraser', '/ɪˈreɪzə(r)/', 'penghapus', 'Can I borrow your eraser?', 'noun', ARRAY['object']::text[], 1),
  ('ruler', '/ˈruːlə(r)/', 'penggaris', 'Use a ruler to draw straight lines.', 'noun', ARRAY['object']::text[], 1),
  ('bag', '/bæɡ/', 'tas', 'My school bag is heavy today.', 'noun', ARRAY['object']::text[], 1),
  ('blackboard', '/ˈblækbɔːd/', 'papan tulis hitam', 'The teacher writes on the blackboard.', 'noun', ARRAY['object']::text[], 1),
  ('whiteboard', '/ˈwaɪtbɔːd/', 'papan tulis putih', 'We use markers on the whiteboard.', 'noun', ARRAY['object']::text[], 1),
  ('chalk', '/tʃɔːk/', 'kapur', 'The teacher needs white chalk.', 'noun', ARRAY['object']::text[], 1),
  ('marker', '/ˈmɑːkə(r)/', 'spidol', 'Use a marker on the whiteboard.', 'noun', ARRAY['object']::text[], 1),
  ('chair', '/tʃeə(r)/', 'kursi', 'Please sit on your chair.', 'noun', ARRAY['furniture']::text[], 1),
  ('desk', '/desk/', 'meja belajar', 'Keep your desk clean and tidy.', 'noun', ARRAY['furniture']::text[], 1),
  ('map', '/mæp/', 'peta', 'Look at the world map.', 'noun', ARRAY['object']::text[], 1),
  ('schedule', '/ˈʃedjuːl/', 'jadwal', 'Check your class schedule.', 'noun', ARRAY['document']::text[], 2),
  ('homework', '/ˈhəʊmwɜːk/', 'PR', 'I have a lot of homework today.', 'noun', ARRAY['task']::text[], 1),
  ('exam', '/ɪɡˈzæm/', 'ujian', 'We have an exam tomorrow.', 'noun', ARRAY['education']::text[], 2),
  ('lesson', '/ˈlesn/', 'pelajaran', 'Today lesson is about animals.', 'noun', ARRAY['education']::text[], 1),
  ('break', '/breɪk/', 'istirahat', 'We have a break at 10 AM.', 'noun', ARRAY['time']::text[], 1),
  ('uniform', '/ˈjuːnɪfɔːm/', 'seragam', 'Wear your school uniform properly.', 'noun', ARRAY['object']::text[], 1),
  ('subject', '/ˈsʌbdʒɪkt/', 'mata pelajaran', 'Math is my favorite subject.', 'noun', ARRAY['education']::text[], 1),
  ('grade', '/ɡreɪd/', 'nilai', 'I got a good grade in English.', 'noun', ARRAY['education']::text[], 1),
  ('report card', '/rɪˈpɔːt kɑːd/', 'rapor', 'My report card is excellent.', 'phrase', ARRAY['document']::text[], 2),
  ('projector', '/prəˈdʒektə(r)/', 'proyektor', 'The teacher uses a projector.', 'noun', ARRAY['equipment']::text[], 2),
  ('computer', '/kəmˈpjuːtə(r)/', 'komputer', 'We learn using computers.', 'noun', ARRAY['equipment']::text[], 1),
  ('laptop', '/ˈlæptɒp/', 'laptop', 'I use a laptop for homework.', 'noun', ARRAY['equipment']::text[], 1),
  ('stapler', '/ˈsteɪplə(r)/', 'stapler', 'I need a stapler for my papers.', 'noun', ARRAY['object']::text[], 2),
  ('scissors', '/ˈsɪzəz/', 'gunting', 'Use scissors carefully.', 'noun', ARRAY['object']::text[], 1),
  ('glue', '/ɡluː/', 'lem', 'We need glue for the art project.', 'noun', ARRAY['object']::text[], 1),
  ('crayon', '/ˈkreɪɒn/', 'krayon', 'Color the picture with crayons.', 'noun', ARRAY['object']::text[], 1),
  ('colored pencil', '/ˈkʌləd ˈpensl/', 'pensil warna', 'I have 24 colored pencils.', 'phrase', ARRAY['object']::text[], 1),
  ('painting', '/ˈpeɪntɪŋ/', 'lukisan', 'This is a beautiful painting.', 'noun', ARRAY['art']::text[], 2),
  ('experiment', '/ɪkˈsperɪmənt/', 'percobaan', 'We did a science experiment.', 'noun', ARRAY['activity']::text[], 2),
  ('microscope', '/ˈmaɪkrəskəʊp/', 'mikroskop', 'Look through the microscope.', 'noun', ARRAY['equipment']::text[], 3),
  ('schoolyard', '/ˈskuːljɑːd/', 'halaman sekolah', 'Children play in the schoolyard.', 'noun', ARRAY['place']::text[], 1),
  ('bell', '/bel/', 'bel sekolah', 'The school bell just rang.', 'noun', ARRAY['object']::text[], 1),
  ('assembly', '/əˈsembli/', 'apel', 'We have assembly every Monday morning.', 'noun', ARRAY['activity']::text[], 2),
  ('notice board', '/ˈnəʊtɪs bɔːd/', 'papan pengumuman', 'Check the notice board daily.', 'phrase', ARRAY['object']::text[], 2),
  ('teacher desk', '/ˈtiːtʃə desk/', 'meja guru', 'The teacher desk is at the front.', 'phrase', ARRAY['furniture']::text[], 1),
  ('bookshelf', '/ˈbʊkʃelf/', 'rak buku', 'Put the books on the bookshelf.', 'noun', ARRAY['furniture']::text[], 1)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- C. NUMBERS AND TIME (70+ words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'numbers-and-time') t
CROSS JOIN (VALUES
  ('one', '/wʌn/', 'satu', 'I have one apple.', 'number', ARRAY['cardinal']::text[], 1),
  ('two', '/tuː/', 'dua', 'She has two books.', 'number', ARRAY['cardinal']::text[], 1),
  ('three', '/θriː/', 'tiga', 'There are three cats.', 'number', ARRAY['cardinal']::text[], 1),
  ('four', '/fɔː(r)/', 'empat', 'I see four birds.', 'number', ARRAY['cardinal']::text[], 1),
  ('five', '/faɪv/', 'lima', 'Give me five minutes.', 'number', ARRAY['cardinal']::text[], 1),
  ('six', '/sɪks/', 'enam', 'Six students are absent.', 'number', ARRAY['cardinal']::text[], 1),
  ('seven', '/ˈsevn/', 'tujuh', 'There are seven days.', 'number', ARRAY['cardinal']::text[], 1),
  ('eight', '/eɪt/', 'delapan', 'I wake up at eight.', 'number', ARRAY['cardinal']::text[], 1),
  ('nine', '/naɪn/', 'sembilan', 'Nine players on the field.', 'number', ARRAY['cardinal']::text[], 1),
  ('ten', '/ten/', 'sepuluh', 'Count to ten.', 'number', ARRAY['cardinal']::text[], 1),
  ('twenty', '/ˈtwenti/', 'dua puluh', 'I am twenty years old.', 'number', ARRAY['cardinal']::text[], 1),
  ('thirty', '/ˈθɜːti/', 'tiga puluh', 'It takes thirty minutes.', 'number', ARRAY['cardinal']::text[], 1),
  ('forty', '/ˈfɔːti/', 'empat puluh', 'Forty students in class.', 'number', ARRAY['cardinal']::text[], 1),
  ('fifty', '/ˈfɪfti/', 'lima puluh', 'The book costs fifty dollars.', 'number', ARRAY['cardinal']::text[], 1),
  ('hundred', '/ˈhʌndrəd/', 'seratus', 'One hundred people came.', 'number', ARRAY['cardinal']::text[], 1),
  ('thousand', '/ˈθaʊznd/', 'seribu', 'One thousand meters.', 'number', ARRAY['cardinal']::text[], 2),
  ('first', '/fɜːst/', 'pertama', 'I came first in the race.', 'ordinal', ARRAY['ordinal']::text[], 1),
  ('second', '/ˈsekənd/', 'kedua', 'This is my second visit.', 'ordinal', ARRAY['ordinal']::text[], 1),
  ('third', '/θɜːd/', 'ketiga', 'She lives on the third floor.', 'ordinal', ARRAY['ordinal']::text[], 1),
  ('fourth', '/fɔːθ/', 'keempat', 'The fourth chapter is interesting.', 'ordinal', ARRAY['ordinal']::text[], 1),
  ('fifth', '/fɪfθ/', 'kelima', 'My birthday is on the fifth.', 'ordinal', ARRAY['ordinal']::text[], 1),
  ('tenth', '/tenθ/', 'kesepuluh', 'Today is the tenth of May.', 'ordinal', ARRAY['ordinal']::text[], 2),
  ('twentieth', '/ˈtwentiəθ/', 'kedua puluh', 'The twentieth century.', 'ordinal', ARRAY['ordinal']::text[], 2),
  ('thirtieth', '/ˈθɜːtiəθ/', 'ketiga puluh', 'Her thirtieth birthday.', 'ordinal', ARRAY['ordinal']::text[], 2),
  ('fiftieth', '/ˈfɪftiəθ/', 'kelima puluh', 'The fiftieth anniversary.', 'ordinal', ARRAY['ordinal']::text[], 2),
  ('hundredth', '/ˈhʌndrədθ/', 'keseratus', 'The hundredth customer.', 'ordinal', ARRAY['ordinal']::text[], 3),
  ('second', '/ˈsekənd/', 'detik', 'Wait a second.', 'noun', ARRAY['time']::text[], 1),
  ('minute', '/ˈmɪnɪt/', 'menit', 'It takes five minutes.', 'noun', ARRAY['time']::text[], 1),
  ('hour', '/ˈaʊə(r)/', 'jam', 'One hour has 60 minutes.', 'noun', ARRAY['time']::text[], 1),
  ('day', '/deɪ/', 'hari', 'Have a nice day.', 'noun', ARRAY['time']::text[], 1),
  ('week', '/wiːk/', 'minggu', 'See you next week.', 'noun', ARRAY['time']::text[], 1),
  ('month', '/mʌnθ/', 'bulan', 'January is the first month.', 'noun', ARRAY['time']::text[], 1),
  ('year', '/jɪə(r)/', 'tahun', 'Happy new year!', 'noun', ARRAY['time']::text[], 1),
  ('today', '/təˈdeɪ/', 'hari ini', 'Today is Monday.', 'noun', ARRAY['time']::text[], 1),
  ('yesterday', '/ˈjestədeɪ/', 'kemarin', 'Yesterday was Sunday.', 'noun', ARRAY['time']::text[], 1),
  ('tomorrow', '/təˈmɒrəʊ/', 'besok', 'See you tomorrow.', 'noun', ARRAY['time']::text[], 1),
  ('morning', '/ˈmɔːnɪŋ/', 'pagi', 'Good morning!', 'noun', ARRAY['time']::text[], 1),
  ('afternoon', '/ˌɑːftəˈnuːn/', 'siang', 'Good afternoon!', 'noun', ARRAY['time']::text[], 1),
  ('evening', '/ˈiːvnɪŋ/', 'sore', 'Good evening!', 'noun', ARRAY['time']::text[], 1),
  ('night', '/naɪt/', 'malam', 'Good night!', 'noun', ARRAY['time']::text[], 1),
  ('midnight', '/ˈmɪdnaɪt/', 'tengah malam', 'The clock struck midnight.', 'noun', ARRAY['time']::text[], 2),
  ('noon', '/nuːn/', 'tengah hari', 'We eat lunch at noon.', 'noun', ARRAY['time']::text[], 2),
  ('o clock', '/əˈklɒk/', 'tepat', 'It is three o clock.', 'phrase', ARRAY['time']::text[], 1),
  ('half past', '/hɑːf pɑːst/', 'setengah', 'It is half past seven.', 'phrase', ARRAY['time']::text[], 2),
  ('quarter past', '/ˈkwɔːtə pɑːst/', 'seperempat lewat', 'Quarter past eight.', 'phrase', ARRAY['time']::text[], 2),
  ('quarter to', '/ˈkwɔːtə tuː/', 'kurang seperempat', 'Quarter to nine.', 'phrase', ARRAY['time']::text[], 2)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- D. COLORS AND SHAPES (50 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'colors-and-shapes') t
CROSS JOIN (VALUES
  ('red', '/red/', 'merah', 'The apple is red.', 'adjective', ARRAY['color']::text[], 1),
  ('blue', '/bluː/', 'biru', 'The sky is blue.', 'adjective', ARRAY['color']::text[], 1),
  ('yellow', '/ˈjeləʊ/', 'kuning', 'The sun is yellow.', 'adjective', ARRAY['color']::text[], 1),
  ('green', '/ɡriːn/', 'hijau', 'Grass is green.', 'adjective', ARRAY['color']::text[], 1),
  ('black', '/blæk/', 'hitam', 'My cat is black.', 'adjective', ARRAY['color']::text[], 1),
  ('white', '/waɪt/', 'putih', 'Snow is white.', 'adjective', ARRAY['color']::text[], 1),
  ('orange', '/ˈɒrɪndʒ/', 'oranye', 'I like orange juice.', 'adjective', ARRAY['color']::text[], 1),
  ('purple', '/ˈpɜːpl/', 'ungu', 'She wears a purple dress.', 'adjective', ARRAY['color']::text[], 1),
  ('pink', '/pɪŋk/', 'pink', 'Pink roses are beautiful.', 'adjective', ARRAY['color']::text[], 1),
  ('brown', '/braʊn/', 'cokelat', 'The bear is brown.', 'adjective', ARRAY['color']::text[], 1),
  ('gray', '/ɡreɪ/', 'abu-abu', 'The elephant is gray.', 'adjective', ARRAY['color']::text[], 1),
  ('silver', '/ˈsɪlvə(r)/', 'perak', 'A silver ring.', 'adjective', ARRAY['color']::text[], 2),
  ('gold', '/ɡəʊld/', 'emas', 'A gold medal.', 'adjective', ARRAY['color']::text[], 2),
  ('light blue', '/laɪt bluː/', 'biru muda', 'Light blue sky.', 'phrase', ARRAY['color']::text[], 2),
  ('dark blue', '/dɑːk bluː/', 'biru tua', 'Dark blue sea.', 'phrase', ARRAY['color']::text[], 2),
  ('navy', '/ˈneɪvi/', 'biru dongker', 'Navy blue uniform.', 'adjective', ARRAY['color']::text[], 2),
  ('light green', '/laɪt ɡriːn/', 'hijau muda', 'Light green leaves.', 'phrase', ARRAY['color']::text[], 2),
  ('dark green', '/dɑːk ɡriːn/', 'hijau tua', 'Dark green forest.', 'phrase', ARRAY['color']::text[], 2),
  ('beige', '/beɪʒ/', 'krem', 'Beige walls.', 'adjective', ARRAY['color']::text[], 3),
  ('violet', '/ˈvaɪələt/', 'ungu violet', 'Violet flowers.', 'adjective', ARRAY['color']::text[], 2),
  ('turquoise', '/ˈtɜːkwɔɪz/', 'toska', 'Turquoise water.', 'adjective', ARRAY['color']::text[], 3),
  ('maroon', '/məˈruːn/', 'merah marun', 'Maroon curtains.', 'adjective', ARRAY['color']::text[], 3),
  ('cream', '/kriːm/', 'krem pucat', 'Cream colored dress.', 'adjective', ARRAY['color']::text[], 2),
  ('lime', '/laɪm/', 'hijau limau', 'Lime green shirt.', 'adjective', ARRAY['color']::text[], 2),
  ('magenta', '/məˈdʒentə/', 'magenta', 'Magenta paint.', 'adjective', ARRAY['color']::text[], 3),
  ('circle', '/ˈsɜːkl/', 'lingkaran', 'Draw a circle.', 'noun', ARRAY['shape']::text[], 1),
  ('oval', '/ˈəʊvl/', 'oval', 'An oval face.', 'noun', ARRAY['shape']::text[], 2),
  ('square', '/skweə(r)/', 'persegi', 'A square box.', 'noun', ARRAY['shape']::text[], 1),
  ('rectangle', '/ˈrektæŋɡl/', 'persegi panjang', 'A rectangle table.', 'noun', ARRAY['shape']::text[], 1),
  ('triangle', '/ˈtraɪæŋɡl/', 'segitiga', 'A triangle has three sides.', 'noun', ARRAY['shape']::text[], 1),
  ('star', '/stɑː(r)/', 'bintang', 'Draw a five-pointed star.', 'noun', ARRAY['shape']::text[], 1),
  ('heart', '/hɑːt/', 'hati', 'A heart shape.', 'noun', ARRAY['shape']::text[], 1),
  ('diamond', '/ˈdaɪəmənd/', 'berlian', 'A diamond shape.', 'noun', ARRAY['shape']::text[], 2),
  ('hexagon', '/ˈheksəɡən/', 'segi enam', 'A hexagon has six sides.', 'noun', ARRAY['shape']::text[], 3),
  ('octagon', '/ˈɒktəɡən/', 'segi delapan', 'An octagon has eight sides.', 'noun', ARRAY['shape']::text[], 3),
  ('arrow', '/ˈærəʊ/', 'panah', 'Follow the arrow.', 'noun', ARRAY['shape']::text[], 1),
  ('line', '/laɪn/', 'garis', 'Draw a straight line.', 'noun', ARRAY['shape']::text[], 1),
  ('curve', '/kɜːv/', 'lengkungan', 'A curve line.', 'noun', ARRAY['shape']::text[], 2),
  ('cube', '/kjuːb/', 'kubus', 'A cube has six faces.', 'noun', ARRAY['shape']::text[], 2),
  ('cone', '/kəʊn/', 'kerucut', 'An ice cream cone.', 'noun', ARRAY['shape']::text[], 2),
  ('cylinder', '/ˈsɪlɪndə(r)/', 'silinder', 'A cylindrical shape.', 'noun', ARRAY['shape']::text[], 3),
  ('sphere', '/sfɪə(r)/', 'bola', 'A sphere is round.', 'noun', ARRAY['shape']::text[], 2),
  ('pyramid', '/ˈpɪrəmɪd/', 'piramida', 'Egyptian pyramids.', 'noun', ARRAY['shape']::text[], 2),
  ('trapezoid', '/ˈtræpəzɔɪd/', 'trapesium', 'A trapezoid shape.', 'noun', ARRAY['shape']::text[], 3),
  ('parallelogram', '/ˌpærəˈleləɡræm/', 'jajar genjang', 'A parallelogram.', 'noun', ARRAY['shape']::text[], 3),
  ('cross', '/krɒs/', 'silang', 'A cross symbol.', 'noun', ARRAY['shape']::text[], 1),
  ('crescent', '/ˈkresnt/', 'bulan sabit', 'A crescent moon.', 'noun', ARRAY['shape']::text[], 2),
  ('spiral', '/ˈspaɪrəl/', 'spiral', 'A spiral staircase.', 'noun', ARRAY['shape']::text[], 3),
  ('semicircle', '/ˈsemiˌsɜːkl/', 'setengah lingkaran', 'A semicircle.', 'noun', ARRAY['shape']::text[], 3),
  ('polygon', '/ˈpɒliɡən/', 'poligon', 'A polygon has many sides.', 'noun', ARRAY['shape']::text[], 3)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- E. DAILY ACTIVITIES (50 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'daily-activities') t
CROSS JOIN (VALUES
  ('wake up', '/weɪk ʌp/', 'bangun tidur', 'I wake up at six.', 'verb', ARRAY['routine']::text[], 1),
  ('get up', '/ɡet ʌp/', 'bangkit dari tempat tidur', 'Get up quickly!', 'verb', ARRAY['routine']::text[], 1),
  ('take a bath', '/teɪk ə bɑːθ/', 'mandi', 'I take a bath every morning.', 'verb', ARRAY['routine']::text[], 1),
  ('brush teeth', '/brʌʃ tiːθ/', 'sikat gigi', 'Brush your teeth twice a day.', 'verb', ARRAY['routine']::text[], 1),
  ('wash face', '/wɒʃ feɪs/', 'cuci muka', 'Wash your face with soap.', 'verb', ARRAY['routine']::text[], 1),
  ('get dressed', '/ɡet drest/', 'berpakaian', 'Get dressed for school.', 'verb', ARRAY['routine']::text[], 1),
  ('comb hair', '/kəʊm heə(r)/', 'sisir rambut', 'Comb your hair neatly.', 'verb', ARRAY['routine']::text[], 1),
  ('have breakfast', '/hæv ˈbrekfəst/', 'sarapan', 'Have breakfast before school.', 'verb', ARRAY['routine']::text[], 1),
  ('go to school', '/ɡəʊ tuː skuːl/', 'pergi sekolah', 'I go to school by bus.', 'verb', ARRAY['routine']::text[], 1),
  ('study', '/ˈstʌdi/', 'belajar', 'I study hard for exams.', 'verb', ARRAY['activity']::text[], 1),
  ('read', '/riːd/', 'membaca', 'I like to read books.', 'verb', ARRAY['activity']::text[], 1),
  ('write', '/raɪt/', 'menulis', 'Write your name here.', 'verb', ARRAY['activity']::text[], 1),
  ('listen to music', '/ˈlɪsn tuː ˈmjuːzɪk/', 'mendengarkan musik', 'I listen to music daily.', 'verb', ARRAY['leisure']::text[], 1),
  ('watch TV', '/wɒtʃ ˌtiː ˈviː/', 'menonton TV', 'Watch TV after homework.', 'verb', ARRAY['leisure']::text[], 1),
  ('play games', '/pleɪ ɡeɪmz/', 'bermain game', 'Play games with friends.', 'verb', ARRAY['leisure']::text[], 1),
  ('play football', '/pleɪ ˈfʊtbɔːl/', 'main bola', 'Play football in the yard.', 'verb', ARRAY['sport']::text[], 1),
  ('ride a bike', '/raɪd ə baɪk/', 'naik sepeda', 'I ride a bike to school.', 'verb', ARRAY['activity']::text[], 1),
  ('help parents', '/help ˈpeərənts/', 'membantu orang tua', 'Help parents at home.', 'verb', ARRAY['chore']::text[], 1),
  ('sweep the floor', '/swiːp ðə flɔː(r)/', 'menyapu', 'Sweep the floor daily.', 'verb', ARRAY['chore']::text[], 1),
  ('wash dishes', '/wɒʃ ˈdɪʃɪz/', 'mencuci piring', 'Wash dishes after eating.', 'verb', ARRAY['chore']::text[], 1),
  ('have lunch', '/hæv lʌntʃ/', 'makan siang', 'Have lunch at noon.', 'verb', ARRAY['routine']::text[], 1),
  ('take a nap', '/teɪk ə næp/', 'tidur siang', 'Take a nap after lunch.', 'verb', ARRAY['routine']::text[], 1),
  ('do homework', '/duː ˈhəʊmwɜːk/', 'mengerjakan PR', 'Do homework every day.', 'verb', ARRAY['routine']::text[], 1),
  ('talk with friends', '/tɔːk wɪð frendz/', 'ngobrol', 'Talk with friends at break.', 'verb', ARRAY['social']::text[], 1),
  ('go shopping', '/ɡəʊ ˈʃɒpɪŋ/', 'belanja', 'Go shopping with mom.', 'verb', ARRAY['activity']::text[], 1),
  ('cook', '/kʊk/', 'memasak', 'My mom cooks delicious food.', 'verb', ARRAY['chore']::text[], 1),
  ('clean the room', '/kliːn ðə ruːm/', 'membersihkan kamar', 'Clean the room every week.', 'verb', ARRAY['chore']::text[], 1),
  ('wash clothes', '/wɒʃ kləʊðz/', 'mencuci baju', 'Wash clothes on weekend.', 'verb', ARRAY['chore']::text[], 1),
  ('iron clothes', '/ˈaɪən kləʊðz/', 'menyetrika', 'Iron clothes before wearing.', 'verb', ARRAY['chore']::text[], 2),
  ('feed pets', '/fiːd pets/', 'memberi makan hewan', 'Feed pets every morning.', 'verb', ARRAY['chore']::text[], 1),
  ('exercise', '/ˈeksəsaɪz/', 'olahraga', 'Exercise keeps you healthy.', 'verb', ARRAY['sport']::text[], 1),
  ('jog', '/dʒɒɡ/', 'lari pagi', 'I jog every morning.', 'verb', ARRAY['sport']::text[], 1),
  ('dance', '/dɑːns/', 'menari', 'She loves to dance.', 'verb', ARRAY['leisure']::text[], 1),
  ('sing', '/sɪŋ/', 'bernyanyi', 'Sing a beautiful song.', 'verb', ARRAY['leisure']::text[], 1),
  ('draw', '/drɔː/', 'menggambar', 'Draw a nice picture.', 'verb', ARRAY['leisure']::text[], 1),
  ('paint', '/peɪnt/', 'melukis', 'Paint with watercolors.', 'verb', ARRAY['leisure']::text[], 1),
  ('write a diary', '/raɪt ə ˈdaɪəri/', 'menulis buku harian', 'Write a diary every night.', 'verb', ARRAY['activity']::text[], 2),
  ('surf the internet', '/sɜːf ði ˈɪntənet/', 'berselancar internet', 'Surf the internet safely.', 'verb', ARRAY['activity']::text[], 2),
  ('chat online', '/tʃæt ˈɒnlaɪn/', 'chat online', 'Chat online with friends.', 'verb', ARRAY['activity']::text[], 1),
  ('go swimming', '/ɡəʊ ˈswɪmɪŋ/', 'berenang', 'Go swimming on Sunday.', 'verb', ARRAY['sport']::text[], 1),
  ('play basketball', '/pleɪ ˈbɑːskɪtbɔːl/', 'main basket', 'Play basketball after school.', 'verb', ARRAY['sport']::text[], 1),
  ('play guitar', '/pleɪ ɡɪˈtɑː(r)/', 'main gitar', 'Play guitar beautifully.', 'verb', ARRAY['leisure']::text[], 2),
  ('go for a walk', '/ɡəʊ fɔːr ə wɔːk/', 'jalan-jalan', 'Go for a walk in the park.', 'verb', ARRAY['leisure']::text[], 1),
  ('pray', '/preɪ/', 'berdoa', 'Pray before eating.', 'verb', ARRAY['routine']::text[], 1),
  ('visit friends', '/ˈvɪzɪt frendz/', 'mengunjungi teman', 'Visit friends on weekend.', 'verb', ARRAY['social']::text[], 1),
  ('rest', '/rest/', 'beristirahat', 'Rest when you are tired.', 'verb', ARRAY['routine']::text[], 1),
  ('go to bed', '/ɡəʊ tuː bed/', 'tidur malam', 'Go to bed early.', 'verb', ARRAY['routine']::text[], 1),
  ('brush hair', '/brʌʃ heə(r)/', 'menyisir rambut', 'Brush hair before sleeping.', 'verb', ARRAY['routine']::text[], 1),
  ('tidy the bed', '/ˈtaɪdi ðə bed/', 'merapikan tempat tidur', 'Tidy the bed every morning.', 'verb', ARRAY['chore']::text[], 1),
  ('pack school bag', '/pæk skuːl bæɡ/', 'menyiapkan tas', 'Pack school bag at night.', 'verb', ARRAY['routine']::text[], 1)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;
