/*
  # Complete Vocabulary Database for All 10 Topics

  This migration adds ALL vocabulary words for all 10 topics:
  - B. School and Classroom (50 words)
  - C. Numbers and Time (46 words)
  - D. Colors and Shapes (50 words)
  - E. Daily Activities (50 words)
  - F. Food and Drinks (70 words)
  - G. Animals (50 words)
  - H. Places (50 words)
  - I. Adjectives (50 words)
  - J. Common Expressions (50 words)

  Total: 466 new words + 50 existing = 516 total words
*/

-- B. SCHOOL AND CLASSROOM (50 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'school-and-classroom') t
CROSS JOIN (VALUES
  ('teacher', '/ˈtiːtʃə(r)/', 'guru', 'The teacher explains the lesson.', 'noun', ARRAY['people']::text[], 1),
  ('student', '/ˈstjuːdnt/', 'murid', 'The students are studying hard.', 'noun', ARRAY['people']::text[], 1),
  ('principal', '/ˈprɪnsəpl/', 'kepala sekolah', 'The principal is very kind.', 'noun', ARRAY['people']::text[], 2),
  ('janitor', '/ˈdʒænɪtə(r)/', 'penjaga sekolah', 'The janitor cleans the school.', 'noun', ARRAY['people']::text[], 2),
  ('classroom', '/ˈklɑːsruːm/', 'ruang kelas', 'Our classroom is clean and bright.', 'noun', ARRAY['place']::text[], 1),
  ('library', '/ˈlaɪbrəri/', 'perpustakaan', 'I borrowed books from the library.', 'noun', ARRAY['place']::text[], 1),
  ('laboratory', '/ləˈbɒrətri/', 'laboratorium', 'We do science experiments in the laboratory.', 'noun', ARRAY['place']::text[], 2),
  ('canteen', '/kænˈtiːn/', 'kantin', 'We eat lunch in the canteen.', 'noun', ARRAY['place']::text[], 1),
  ('book', '/bʊk/', 'buku', 'I read an interesting book.', 'noun', ARRAY['object']::text[], 1),
  ('notebook', '/ˈnəʊtbʊk/', 'buku catatan', 'Write notes in your notebook.', 'noun', ARRAY['object']::text[], 1),
  ('dictionary', '/ˈdɪkʃənri/', 'kamus', 'Use a dictionary to find word meanings.', 'noun', ARRAY['object']::text[], 2),
  ('pen', '/pen/', 'pena', 'I write with a blue pen.', 'noun', ARRAY['object']::text[], 1),
  ('pencil', '/ˈpensl/', 'pensil', 'Please lend me a pencil.', 'noun', ARRAY['object']::text[], 1),
  ('sharpener', '/ˈʃɑːpnə(r)/', 'serutan', 'I need a pencil sharpener.', 'noun', ARRAY['object']::text[], 1),
  ('eraser', '/ɪˈreɪzə(r)/', 'penghapus', 'Can I borrow your eraser?', 'noun', ARRAY['object']::text[], 1),
  ('ruler', '/ˈruːlə(r)/', 'penggaris', 'Use a ruler to draw straight lines.', 'noun', ARRAY['object']::text[], 1),
  ('bag', '/bæɡ/', 'tas', 'My school bag is heavy today.', 'noun', ARRAY['object']::text[], 1),
  ('blackboard', '/ˈblækbɔːd/', 'papan tulis hitam', 'The teacher writes on the blackboard.', 'noun', ARRAY['object']::text[], 1),
  ('whiteboard', '/ˈwaɪtbɔːd/', 'papan tulis putih', 'We use markers on the whiteboard.', 'noun', ARRAY['object']::text[], 1),
  ('chalk', '/tʃɔːk/', 'kapur', 'The teacher needs white chalk.', 'noun', ARRAY['object']::text[], 1),
  ('marker', '/ˈmɑːkə(r)/', 'spidol', 'Use a marker on the whiteboard.', 'noun', ARRAY['object']::text[], 1),
  ('chair', '/tʃeə(r)/', 'kursi', 'Please sit on your chair.', 'noun', ARRAY['furniture']::text[], 1),
  ('desk', '/desk/', 'meja belajar', 'Keep your desk clean and tidy.', 'noun', ARRAY['furniture']::text[], 1),
  ('map', '/mæp/', 'peta', 'Look at the world map.', 'noun', ARRAY['object']::text[], 1),
  ('schedule', '/ˈʃedjuːl/', 'jadwal', 'Check your class schedule.', 'noun', ARRAY['document']::text[], 2),
  ('homework', '/ˈhəʊmwɜːk/', 'PR', 'I have a lot of homework today.', 'noun', ARRAY['task']::text[], 1),
  ('exam', '/ɪɡˈzæm/', 'ujian', 'We have an exam tomorrow.', 'noun', ARRAY['education']::text[], 2),
  ('lesson', '/ˈlesn/', 'pelajaran', 'Today lesson is about animals.', 'noun', ARRAY['education']::text[], 1),
  ('break', '/breɪk/', 'istirahat', 'We have a break at 10 AM.', 'noun', ARRAY['time']::text[], 1),
  ('uniform', '/ˈjuːnɪfɔːm/', 'seragam', 'Wear your school uniform properly.', 'noun', ARRAY['object']::text[], 1),
  ('subject', '/ˈsʌbdʒɪkt/', 'mata pelajaran', 'Math is my favorite subject.', 'noun', ARRAY['education']::text[], 1),
  ('grade', '/ɡreɪd/', 'nilai', 'I got a good grade in English.', 'noun', ARRAY['education']::text[], 1),
  ('report card', '/rɪˈpɔːt kɑːd/', 'rapor', 'My report card is excellent.', 'phrase', ARRAY['document']::text[], 2),
  ('projector', '/prəˈdʒektə(r)/', 'proyektor', 'The teacher uses a projector.', 'noun', ARRAY['equipment']::text[], 2),
  ('computer', '/kəmˈpjuːtə(r)/', 'komputer', 'We learn using computers.', 'noun', ARRAY['equipment']::text[], 1),
  ('laptop', '/ˈlæptɒp/', 'laptop', 'I use a laptop for homework.', 'noun', ARRAY['equipment']::text[], 1),
  ('stapler', '/ˈsteɪplə(r)/', 'stapler', 'I need a stapler for my papers.', 'noun', ARRAY['object']::text[], 2),
  ('scissors', '/ˈsɪzəz/', 'gunting', 'Use scissors carefully.', 'noun', ARRAY['object']::text[], 1),
  ('glue', '/ɡluː/', 'lem', 'We need glue for the art project.', 'noun', ARRAY['object']::text[], 1),
  ('crayon', '/ˈkreɪɒn/', 'krayon', 'Color the picture with crayons.', 'noun', ARRAY['object']::text[], 1),
  ('colored pencil', '/ˈkʌləd ˈpensl/', 'pensil warna', 'I have 24 colored pencils.', 'phrase', ARRAY['object']::text[], 1),
  ('painting', '/ˈpeɪntɪŋ/', 'lukisan', 'This is a beautiful painting.', 'noun', ARRAY['art']::text[], 2),
  ('experiment', '/ɪkˈsperɪmənt/', 'percobaan', 'We did a science experiment.', 'noun', ARRAY['activity']::text[], 2),
  ('microscope', '/ˈmaɪkrəskəʊp/', 'mikroskop', 'Look through the microscope.', 'noun', ARRAY['equipment']::text[], 3),
  ('schoolyard', '/ˈskuːljɑːd/', 'halaman sekolah', 'Children play in the schoolyard.', 'noun', ARRAY['place']::text[], 1),
  ('bell', '/bel/', 'bel sekolah', 'The school bell just rang.', 'noun', ARRAY['object']::text[], 1),
  ('assembly', '/əˈsembli/', 'apel', 'We have assembly every Monday morning.', 'noun', ARRAY['activity']::text[], 2),
  ('notice board', '/ˈnəʊtɪs bɔːd/', 'papan pengumuman', 'Check the notice board daily.', 'phrase', ARRAY['object']::text[], 2),
  ('teacher desk', '/ˈtiːtʃə desk/', 'meja guru', 'The teacher desk is at the front.', 'phrase', ARRAY['furniture']::text[], 1),
  ('bookshelf', '/ˈbʊkʃelf/', 'rak buku', 'Put the books on the bookshelf.', 'noun', ARRAY['furniture']::text[], 1)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- C. NUMBERS AND TIME (46 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'numbers-and-time') t
CROSS JOIN (VALUES
  ('one', '/wʌn/', 'satu', 'I have one apple.', 'number', ARRAY['cardinal']::text[], 1),
  ('two', '/tuː/', 'dua', 'She has two books.', 'number', ARRAY['cardinal']::text[], 1),
  ('three', '/θriː/', 'tiga', 'There are three cats.', 'number', ARRAY['cardinal']::text[], 1),
  ('four', '/fɔː(r)/', 'empat', 'I see four birds.', 'number', ARRAY['cardinal']::text[], 1),
  ('five', '/faɪv/', 'lima', 'Give me five minutes.', 'number', ARRAY['cardinal']::text[], 1),
  ('ten', '/ten/', 'sepuluh', 'Count to ten.', 'number', ARRAY['cardinal']::text[], 1),
  ('twenty', '/ˈtwenti/', 'dua puluh', 'I am twenty years old.', 'number', ARRAY['cardinal']::text[], 1),
  ('thirty', '/ˈθɜːti/', 'tiga puluh', 'It takes thirty minutes.', 'number', ARRAY['cardinal']::text[], 1),
  ('fifty', '/ˈfɪfti/', 'lima puluh', 'The book costs fifty dollars.', 'number', ARRAY['cardinal']::text[], 1),
  ('hundred', '/ˈhʌndrəd/', 'seratus', 'One hundred people came.', 'number', ARRAY['cardinal']::text[], 1),
  ('thousand', '/ˈθaʊznd/', 'seribu', 'One thousand meters.', 'number', ARRAY['cardinal']::text[], 2),
  ('first', '/fɜːst/', 'pertama', 'I came first in the race.', 'ordinal', ARRAY['ordinal']::text[], 1),
  ('second', '/ˈsekənd/', 'kedua', 'This is my second visit.', 'ordinal', ARRAY['ordinal']::text[], 1),
  ('third', '/θɜːd/', 'ketiga', 'She lives on the third floor.', 'ordinal', ARRAY['ordinal']::text[], 1),
  ('fourth', '/fɔːθ/', 'keempat', 'The fourth chapter is interesting.', 'ordinal', ARRAY['ordinal']::text[], 1),
  ('fifth', '/fɪfθ/', 'kelima', 'My birthday is on the fifth.', 'ordinal', ARRAY['ordinal']::text[], 1),
  ('tenth', '/tenθ/', 'kesepuluh', 'Today is the tenth of May.', 'ordinal', ARRAY['ordinal']::text[], 2),
  ('twentieth', '/ˈtwentiəθ/', 'kedua puluh', 'The twentieth century.', 'ordinal', ARRAY['ordinal']::text[], 2),
  ('thirtieth', '/ˈθɜːtiəθ/', 'ketiga puluh', 'Her thirtieth birthday.', 'ordinal', ARRAY['ordinal']::text[], 2),
  ('fiftieth', '/ˈfɪftiəθ/', 'kelima puluh', 'The fiftieth anniversary.', 'ordinal', ARRAY['ordinal']::text[], 2),
  ('hundredth', '/ˈhʌndrədθ/', 'keseratus', 'The hundredth customer.', 'ordinal', ARRAY['ordinal']::text[], 3),
  ('minute', '/ˈmɪnɪt/', 'menit', 'It takes five minutes.', 'noun', ARRAY['time']::text[], 1),
  ('hour', '/ˈaʊə(r)/', 'jam', 'One hour has 60 minutes.', 'noun', ARRAY['time']::text[], 1),
  ('day', '/deɪ/', 'hari', 'Have a nice day.', 'noun', ARRAY['time']::text[], 1),
  ('week', '/wiːk/', 'minggu', 'See you next week.', 'noun', ARRAY['time']::text[], 1),
  ('month', '/mʌnθ/', 'bulan', 'January is the first month.', 'noun', ARRAY['time']::text[], 1),
  ('year', '/jɪə(r)/', 'tahun', 'Happy new year!', 'noun', ARRAY['time']::text[], 1),
  ('today', '/təˈdeɪ/', 'hari ini', 'Today is Monday.', 'noun', ARRAY['time']::text[], 1),
  ('yesterday', '/ˈjestədeɪ/', 'kemarin', 'Yesterday was Sunday.', 'noun', ARRAY['time']::text[], 1),
  ('tomorrow', '/təˈmɒrəʊ/', 'besok', 'See you tomorrow.', 'noun', ARRAY['time']::text[], 1),
  ('morning', '/ˈmɔːnɪŋ/', 'pagi', 'Good morning!', 'noun', ARRAY['time']::text[], 1),
  ('afternoon', '/ˌɑːftəˈnuːn/', 'siang', 'Good afternoon!', 'noun', ARRAY['time']::text[], 1),
  ('evening', '/ˈiːvnɪŋ/', 'sore', 'Good evening!', 'noun', ARRAY['time']::text[], 1),
  ('night', '/naɪt/', 'malam', 'Good night!', 'noun', ARRAY['time']::text[], 1),
  ('midnight', '/ˈmɪdnaɪt/', 'tengah malam', 'The clock struck midnight.', 'noun', ARRAY['time']::text[], 2),
  ('noon', '/nuːn/', 'tengah hari', 'We eat lunch at noon.', 'noun', ARRAY['time']::text[], 2),
  ('o clock', '/əˈklɒk/', 'tepat', 'It is three o clock.', 'phrase', ARRAY['time']::text[], 1),
  ('half past', '/hɑːf pɑːst/', 'setengah', 'It is half past seven.', 'phrase', ARRAY['time']::text[], 2),
  ('quarter past', '/ˈkwɔːtə pɑːst/', 'seperempat lewat', 'Quarter past eight.', 'phrase', ARRAY['time']::text[], 2),
  ('quarter to', '/ˈkwɔːtə tuː/', 'kurang seperempat', 'Quarter to nine.', 'phrase', ARRAY['time']::text[], 2),
  ('six', '/sɪks/', 'enam', 'Six students are here.', 'number', ARRAY['cardinal']::text[], 1),
  ('seven', '/ˈsevn/', 'tujuh', 'Seven days a week.', 'number', ARRAY['cardinal']::text[], 1),
  ('eight', '/eɪt/', 'delapan', 'I wake up at eight.', 'number', ARRAY['cardinal']::text[], 1),
  ('nine', '/naɪn/', 'sembilan', 'Nine players on field.', 'number', ARRAY['cardinal']::text[], 1),
  ('forty', '/ˈfɔːti/', 'empat puluh', 'Forty students in class.', 'number', ARRAY['cardinal']::text[], 1),
  ('time', '/taɪm/', 'waktu', 'What time is it?', 'noun', ARRAY['time']::text[], 1)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- D. COLORS AND SHAPES (50 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'colors-and-shapes') t
CROSS JOIN (VALUES
  ('red', '/red/', 'merah', 'The apple is red.', 'adjective', ARRAY['color']::text[], 1),
  ('blue', '/bluː/', 'biru', 'The sky is blue.', 'adjective', ARRAY['color']::text[], 1),
  ('yellow', '/ˈjeləʊ/', 'kuning', 'The sun is yellow.', 'adjective', ARRAY['color']::text[], 1),
  ('green', '/ɡriːn/', 'hijau', 'Grass is green.', 'adjective', ARRAY['color']::text[], 1),
  ('black', '/blæk/', 'hitam', 'My cat is black.', 'adjective', ARRAY['color']::text[], 1),
  ('white', '/waɪt/', 'putih', 'Snow is white.', 'adjective', ARRAY['color']::text[], 1),
  ('orange', '/ˈɒrɪndʒ/', 'oranye', 'I like orange juice.', 'adjective', ARRAY['color']::text[], 1),
  ('purple', '/ˈpɜːpl/', 'ungu', 'She wears a purple dress.', 'adjective', ARRAY['color']::text[], 1),
  ('pink', '/pɪŋk/', 'pink', 'Pink roses are beautiful.', 'adjective', ARRAY['color']::text[], 1),
  ('brown', '/braʊn/', 'cokelat', 'The bear is brown.', 'adjective', ARRAY['color']::text[], 1),
  ('gray', '/ɡreɪ/', 'abu-abu', 'The elephant is gray.', 'adjective', ARRAY['color']::text[], 1),
  ('silver', '/ˈsɪlvə(r)/', 'perak', 'A silver ring.', 'adjective', ARRAY['color']::text[], 2),
  ('gold', '/ɡəʊld/', 'emas', 'A gold medal.', 'adjective', ARRAY['color']::text[], 2),
  ('light blue', '/laɪt bluː/', 'biru muda', 'Light blue sky.', 'phrase', ARRAY['color']::text[], 2),
  ('dark blue', '/dɑːk bluː/', 'biru tua', 'Dark blue sea.', 'phrase', ARRAY['color']::text[], 2),
  ('navy', '/ˈneɪvi/', 'biru dongker', 'Navy blue uniform.', 'adjective', ARRAY['color']::text[], 2),
  ('light green', '/laɪt ɡriːn/', 'hijau muda', 'Light green leaves.', 'phrase', ARRAY['color']::text[], 2),
  ('dark green', '/dɑːk ɡriːn/', 'hijau tua', 'Dark green forest.', 'phrase', ARRAY['color']::text[], 2),
  ('beige', '/beɪʒ/', 'krem', 'Beige walls.', 'adjective', ARRAY['color']::text[], 3),
  ('violet', '/ˈvaɪələt/', 'ungu violet', 'Violet flowers.', 'adjective', ARRAY['color']::text[], 2),
  ('turquoise', '/ˈtɜːkwɔɪz/', 'toska', 'Turquoise water.', 'adjective', ARRAY['color']::text[], 3),
  ('maroon', '/məˈruːn/', 'merah marun', 'Maroon curtains.', 'adjective', ARRAY['color']::text[], 3),
  ('cream', '/kriːm/', 'krem pucat', 'Cream colored dress.', 'adjective', ARRAY['color']::text[], 2),
  ('lime', '/laɪm/', 'hijau limau', 'Lime green shirt.', 'adjective', ARRAY['color']::text[], 2),
  ('magenta', '/məˈdʒentə/', 'magenta', 'Magenta paint.', 'adjective', ARRAY['color']::text[], 3),
  ('circle', '/ˈsɜːkl/', 'lingkaran', 'Draw a circle.', 'noun', ARRAY['shape']::text[], 1),
  ('oval', '/ˈəʊvl/', 'oval', 'An oval face.', 'noun', ARRAY['shape']::text[], 2),
  ('square', '/skweə(r)/', 'persegi', 'A square box.', 'noun', ARRAY['shape']::text[], 1),
  ('rectangle', '/ˈrektæŋɡl/', 'persegi panjang', 'A rectangle table.', 'noun', ARRAY['shape']::text[], 1),
  ('triangle', '/ˈtraɪæŋɡl/', 'segitiga', 'A triangle has three sides.', 'noun', ARRAY['shape']::text[], 1),
  ('star', '/stɑː(r)/', 'bintang', 'Draw a five-pointed star.', 'noun', ARRAY['shape']::text[], 1),
  ('heart', '/hɑːt/', 'hati', 'A heart shape.', 'noun', ARRAY['shape']::text[], 1),
  ('diamond', '/ˈdaɪəmənd/', 'berlian', 'A diamond shape.', 'noun', ARRAY['shape']::text[], 2),
  ('hexagon', '/ˈheksəɡən/', 'segi enam', 'A hexagon has six sides.', 'noun', ARRAY['shape']::text[], 3),
  ('octagon', '/ˈɒktəɡən/', 'segi delapan', 'An octagon has eight sides.', 'noun', ARRAY['shape']::text[], 3),
  ('arrow', '/ˈærəʊ/', 'panah', 'Follow the arrow.', 'noun', ARRAY['shape']::text[], 1),
  ('line', '/laɪn/', 'garis', 'Draw a straight line.', 'noun', ARRAY['shape']::text[], 1),
  ('curve', '/kɜːv/', 'lengkungan', 'A curve line.', 'noun', ARRAY['shape']::text[], 2),
  ('cube', '/kjuːb/', 'kubus', 'A cube has six faces.', 'noun', ARRAY['shape']::text[], 2),
  ('cone', '/kəʊn/', 'kerucut', 'An ice cream cone.', 'noun', ARRAY['shape']::text[], 2),
  ('cylinder', '/ˈsɪlɪndə(r)/', 'silinder', 'A cylindrical shape.', 'noun', ARRAY['shape']::text[], 3),
  ('sphere', '/sfɪə(r)/', 'bola', 'A sphere is round.', 'noun', ARRAY['shape']::text[], 2),
  ('pyramid', '/ˈpɪrəmɪd/', 'piramida', 'Egyptian pyramids.', 'noun', ARRAY['shape']::text[], 2),
  ('trapezoid', '/ˈtræpəzɔɪd/', 'trapesium', 'A trapezoid shape.', 'noun', ARRAY['shape']::text[], 3),
  ('parallelogram', '/ˌpærəˈleləɡræm/', 'jajar genjang', 'A parallelogram.', 'noun', ARRAY['shape']::text[], 3),
  ('cross', '/krɒs/', 'silang', 'A cross symbol.', 'noun', ARRAY['shape']::text[], 1),
  ('crescent', '/ˈkresnt/', 'bulan sabit', 'A crescent moon.', 'noun', ARRAY['shape']::text[], 2),
  ('spiral', '/ˈspaɪrəl/', 'spiral', 'A spiral staircase.', 'noun', ARRAY['shape']::text[], 3),
  ('semicircle', '/ˈsemiˌsɜːkl/', 'setengah lingkaran', 'A semicircle.', 'noun', ARRAY['shape']::text[], 3),
  ('polygon', '/ˈpɒliɡən/', 'poligon', 'A polygon has many sides.', 'noun', ARRAY['shape']::text[], 3)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- E. DAILY ACTIVITIES (50 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'daily-activities') t
CROSS JOIN (VALUES
  ('wake up', '/weɪk ʌp/', 'bangun tidur', 'I wake up at six.', 'verb', ARRAY['routine']::text[], 1),
  ('get up', '/ɡet ʌp/', 'bangkit dari tempat tidur', 'Get up quickly!', 'verb', ARRAY['routine']::text[], 1),
  ('take a bath', '/teɪk ə bɑːθ/', 'mandi', 'I take a bath every morning.', 'verb', ARRAY['routine']::text[], 1),
  ('brush teeth', '/brʌʃ tiːθ/', 'sikat gigi', 'Brush your teeth twice a day.', 'verb', ARRAY['routine']::text[], 1),
  ('wash face', '/wɒʃ feɪs/', 'cuci muka', 'Wash your face with soap.', 'verb', ARRAY['routine']::text[], 1),
  ('get dressed', '/ɡet drest/', 'berpakaian', 'Get dressed for school.', 'verb', ARRAY['routine']::text[], 1),
  ('comb hair', '/kəʊm heə(r)/', 'sisir rambut', 'Comb your hair neatly.', 'verb', ARRAY['routine']::text[], 1),
  ('have breakfast', '/hæv ˈbrekfəst/', 'sarapan', 'Have breakfast before school.', 'verb', ARRAY['routine']::text[], 1),
  ('go to school', '/ɡəʊ tuː skuːl/', 'pergi sekolah', 'I go to school by bus.', 'verb', ARRAY['routine']::text[], 1),
  ('study', '/ˈstʌdi/', 'belajar', 'I study hard for exams.', 'verb', ARRAY['activity']::text[], 1),
  ('read', '/riːd/', 'membaca', 'I like to read books.', 'verb', ARRAY['activity']::text[], 1),
  ('write', '/raɪt/', 'menulis', 'Write your name here.', 'verb', ARRAY['activity']::text[], 1),
  ('listen to music', '/ˈlɪsn tuː ˈmjuːzɪk/', 'mendengarkan musik', 'I listen to music daily.', 'verb', ARRAY['leisure']::text[], 1),
  ('watch TV', '/wɒtʃ ˌtiː ˈviː/', 'menonton TV', 'Watch TV after homework.', 'verb', ARRAY['leisure']::text[], 1),
  ('play games', '/pleɪ ɡeɪmz/', 'bermain game', 'Play games with friends.', 'verb', ARRAY['leisure']::text[], 1),
  ('play football', '/pleɪ ˈfʊtbɔːl/', 'main bola', 'Play football in the yard.', 'verb', ARRAY['sport']::text[], 1),
  ('ride a bike', '/raɪd ə baɪk/', 'naik sepeda', 'I ride a bike to school.', 'verb', ARRAY['activity']::text[], 1),
  ('help parents', '/help ˈpeərənts/', 'membantu orang tua', 'Help parents at home.', 'verb', ARRAY['chore']::text[], 1),
  ('sweep the floor', '/swiːp ðə flɔː(r)/', 'menyapu', 'Sweep the floor daily.', 'verb', ARRAY['chore']::text[], 1),
  ('wash dishes', '/wɒʃ ˈdɪʃɪz/', 'mencuci piring', 'Wash dishes after eating.', 'verb', ARRAY['chore']::text[], 1),
  ('have lunch', '/hæv lʌntʃ/', 'makan siang', 'Have lunch at noon.', 'verb', ARRAY['routine']::text[], 1),
  ('take a nap', '/teɪk ə næp/', 'tidur siang', 'Take a nap after lunch.', 'verb', ARRAY['routine']::text[], 1),
  ('do homework', '/duː ˈhəʊmwɜːk/', 'mengerjakan PR', 'Do homework every day.', 'verb', ARRAY['routine']::text[], 1),
  ('talk with friends', '/tɔːk wɪð frendz/', 'ngobrol', 'Talk with friends at break.', 'verb', ARRAY['social']::text[], 1),
  ('go shopping', '/ɡəʊ ˈʃɒpɪŋ/', 'belanja', 'Go shopping with mom.', 'verb', ARRAY['activity']::text[], 1),
  ('cook', '/kʊk/', 'memasak', 'My mom cooks delicious food.', 'verb', ARRAY['chore']::text[], 1),
  ('clean the room', '/kliːn ðə ruːm/', 'membersihkan kamar', 'Clean the room every week.', 'verb', ARRAY['chore']::text[], 1),
  ('wash clothes', '/wɒʃ kləʊðz/', 'mencuci baju', 'Wash clothes on weekend.', 'verb', ARRAY['chore']::text[], 1),
  ('iron clothes', '/ˈaɪən kləʊðz/', 'menyetrika', 'Iron clothes before wearing.', 'verb', ARRAY['chore']::text[], 2),
  ('feed pets', '/fiːd pets/', 'memberi makan hewan', 'Feed pets every morning.', 'verb', ARRAY['chore']::text[], 1),
  ('exercise', '/ˈeksəsaɪz/', 'olahraga', 'Exercise keeps you healthy.', 'verb', ARRAY['sport']::text[], 1),
  ('jog', '/dʒɒɡ/', 'lari pagi', 'I jog every morning.', 'verb', ARRAY['sport']::text[], 1),
  ('dance', '/dɑːns/', 'menari', 'She loves to dance.', 'verb', ARRAY['leisure']::text[], 1),
  ('sing', '/sɪŋ/', 'bernyanyi', 'Sing a beautiful song.', 'verb', ARRAY['leisure']::text[], 1),
  ('draw', '/drɔː/', 'menggambar', 'Draw a nice picture.', 'verb', ARRAY['leisure']::text[], 1),
  ('paint', '/peɪnt/', 'melukis', 'Paint with watercolors.', 'verb', ARRAY['leisure']::text[], 1),
  ('write a diary', '/raɪt ə ˈdaɪəri/', 'menulis buku harian', 'Write a diary every night.', 'verb', ARRAY['activity']::text[], 2),
  ('surf the internet', '/sɜːf ði ˈɪntənet/', 'berselancar internet', 'Surf the internet safely.', 'verb', ARRAY['activity']::text[], 2),
  ('chat online', '/tʃæt ˈɒnlaɪn/', 'chat online', 'Chat online with friends.', 'verb', ARRAY['activity']::text[], 1),
  ('go swimming', '/ɡəʊ ˈswɪmɪŋ/', 'berenang', 'Go swimming on Sunday.', 'verb', ARRAY['sport']::text[], 1),
  ('play basketball', '/pleɪ ˈbɑːskɪtbɔːl/', 'main basket', 'Play basketball after school.', 'verb', ARRAY['sport']::text[], 1),
  ('play guitar', '/pleɪ ɡɪˈtɑː(r)/', 'main gitar', 'Play guitar beautifully.', 'verb', ARRAY['leisure']::text[], 2),
  ('go for a walk', '/ɡəʊ fɔːr ə wɔːk/', 'jalan-jalan', 'Go for a walk in the park.', 'verb', ARRAY['leisure']::text[], 1),
  ('pray', '/preɪ/', 'berdoa', 'Pray before eating.', 'verb', ARRAY['routine']::text[], 1),
  ('visit friends', '/ˈvɪzɪt frendz/', 'mengunjungi teman', 'Visit friends on weekend.', 'verb', ARRAY['social']::text[], 1),
  ('rest', '/rest/', 'beristirahat', 'Rest when you are tired.', 'verb', ARRAY['routine']::text[], 1),
  ('go to bed', '/ɡəʊ tuː bed/', 'tidur malam', 'Go to bed early.', 'verb', ARRAY['routine']::text[], 1),
  ('brush hair', '/brʌʃ heə(r)/', 'menyisir rambut', 'Brush hair before sleeping.', 'verb', ARRAY['routine']::text[], 1),
  ('tidy the bed', '/ˈtaɪdi ðə bed/', 'merapikan tempat tidur', 'Tidy the bed every morning.', 'verb', ARRAY['chore']::text[], 1),
  ('pack school bag', '/pæk skuːl bæɡ/', 'menyiapkan tas', 'Pack school bag at night.', 'verb', ARRAY['routine']::text[], 1)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- F. FOOD AND DRINKS (70 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'food-and-drinks') t
CROSS JOIN (VALUES
  ('rice', '/raɪs/', 'nasi', 'I eat rice every day.', 'noun', ARRAY['food', 'staple']::text[], 1),
  ('bread', '/bred/', 'roti', 'I like fresh bread.', 'noun', ARRAY['food', 'staple']::text[], 1),
  ('noodle', '/ˈnuːdl/', 'mi', 'Noodle soup is delicious.', 'noun', ARRAY['food', 'staple']::text[], 1),
  ('egg', '/eɡ/', 'telur', 'I eat eggs for breakfast.', 'noun', ARRAY['food', 'protein']::text[], 1),
  ('chicken', '/ˈtʃɪkɪn/', 'ayam', 'Fried chicken is tasty.', 'noun', ARRAY['food', 'meat']::text[], 1),
  ('fish', '/fɪʃ/', 'ikan', 'Fresh fish from the sea.', 'noun', ARRAY['food', 'protein']::text[], 1),
  ('meat', '/miːt/', 'daging', 'I like grilled meat.', 'noun', ARRAY['food', 'protein']::text[], 1),
  ('beef', '/biːf/', 'daging sapi', 'Beef steak is expensive.', 'noun', ARRAY['food', 'meat']::text[], 2),
  ('pork', '/pɔːk/', 'daging babi', 'Pork chops for dinner.', 'noun', ARRAY['food', 'meat']::text[], 2),
  ('lamb', '/læm/', 'daging domba', 'Roasted lamb is tender.', 'noun', ARRAY['food', 'meat']::text[], 3),
  ('soup', '/suːp/', 'sup', 'Hot soup warms me up.', 'noun', ARRAY['food', 'dish']::text[], 1),
  ('salad', '/ˈsæləd/', 'salad', 'Fresh vegetable salad.', 'noun', ARRAY['food', 'dish']::text[], 1),
  ('sandwich', '/ˈsænwɪtʃ/', 'roti isi', 'A ham and cheese sandwich.', 'noun', ARRAY['food', 'dish']::text[], 1),
  ('pizza', '/ˈpiːtsə/', 'pizza', 'Pizza with extra cheese.', 'noun', ARRAY['food', 'dish']::text[], 1),
  ('hamburger', '/ˈhæmbɜːɡə(r)/', 'hamburger', 'A big juicy hamburger.', 'noun', ARRAY['food', 'dish']::text[], 1),
  ('hotdog', '/ˈhɒtdɒɡ/', 'hotdog', 'Hotdog with mustard.', 'noun', ARRAY['food', 'dish']::text[], 1),
  ('cheese', '/tʃiːz/', 'keju', 'I love cheddar cheese.', 'noun', ARRAY['food', 'dairy']::text[], 1),
  ('butter', '/ˈbʌtə(r)/', 'mentega', 'Spread butter on bread.', 'noun', ARRAY['food', 'dairy']::text[], 1),
  ('cake', '/keɪk/', 'kue', 'Birthday cake with candles.', 'noun', ARRAY['food', 'dessert']::text[], 1),
  ('cookies', '/ˈkʊkiz/', 'kue kering', 'Chocolate chip cookies.', 'noun', ARRAY['food', 'dessert']::text[], 1),
  ('ice cream', '/ˈaɪs kriːm/', 'es krim', 'Vanilla ice cream is my favorite.', 'noun', ARRAY['food', 'dessert']::text[], 1),
  ('fruit', '/fruːt/', 'buah', 'Eat fresh fruit daily.', 'noun', ARRAY['food', 'fruit']::text[], 1),
  ('apple', '/ˈæpl/', 'apel', 'A red apple a day.', 'noun', ARRAY['food', 'fruit']::text[], 1),
  ('banana', '/bəˈnɑːnə/', 'pisang', 'Yellow ripe banana.', 'noun', ARRAY['food', 'fruit']::text[], 1),
  ('orange', '/ˈɒrɪndʒ/', 'jeruk', 'Sweet orange juice.', 'noun', ARRAY['food', 'fruit']::text[], 1),
  ('mango', '/ˈmæŋɡəʊ/', 'mangga', 'Tropical mango is sweet.', 'noun', ARRAY['food', 'fruit']::text[], 1),
  ('watermelon', '/ˈwɔːtəmelən/', 'semangka', 'Cool watermelon in summer.', 'noun', ARRAY['food', 'fruit']::text[], 1),
  ('grape', '/ɡreɪp/', 'anggur', 'Purple grapes are juicy.', 'noun', ARRAY['food', 'fruit']::text[], 1),
  ('pineapple', '/ˈpaɪnæpl/', 'nanas', 'Fresh pineapple juice.', 'noun', ARRAY['food', 'fruit']::text[], 2),
  ('strawberry', '/ˈstrɔːbəri/', 'stroberi', 'Sweet red strawberries.', 'noun', ARRAY['food', 'fruit']::text[], 1),
  ('pear', '/peə(r)/', 'pir', 'Green pear is crunchy.', 'noun', ARRAY['food', 'fruit']::text[], 2),
  ('papaya', '/pəˈpaɪə/', 'pepaya', 'Orange papaya flesh.', 'noun', ARRAY['food', 'fruit']::text[], 2),
  ('cherry', '/ˈtʃeri/', 'ceri', 'Red cherry on top.', 'noun', ARRAY['food', 'fruit']::text[], 2),
  ('peach', '/piːtʃ/', 'persik', 'Fuzzy peach skin.', 'noun', ARRAY['food', 'fruit']::text[], 2),
  ('vegetable', '/ˈvedʒtəbl/', 'sayuran', 'Eat green vegetables.', 'noun', ARRAY['food', 'vegetable']::text[], 1),
  ('carrot', '/ˈkærət/', 'wortel', 'Orange carrots are healthy.', 'noun', ARRAY['food', 'vegetable']::text[], 1),
  ('spinach', '/ˈspɪnɪtʃ/', 'bayam', 'Fresh spinach leaves.', 'noun', ARRAY['food', 'vegetable']::text[], 2),
  ('cabbage', '/ˈkæbɪdʒ/', 'kol', 'Green cabbage head.', 'noun', ARRAY['food', 'vegetable']::text[], 2),
  ('tomato', '/təˈmɑːtəʊ/', 'tomat', 'Red ripe tomato.', 'noun', ARRAY['food', 'vegetable']::text[], 1),
  ('cucumber', '/ˈkjuːkʌmbə(r)/', 'mentimun', 'Cool cucumber slices.', 'noun', ARRAY['food', 'vegetable']::text[], 1),
  ('potato', '/pəˈteɪtəʊ/', 'kentang', 'Mashed potatoes are soft.', 'noun', ARRAY['food', 'vegetable']::text[], 1),
  ('corn', '/kɔːn/', 'jagung', 'Sweet corn kernels.', 'noun', ARRAY['food', 'vegetable']::text[], 1),
  ('onion', '/ˈʌnjən/', 'bawang', 'Chopped onion makes me cry.', 'noun', ARRAY['food', 'vegetable']::text[], 1),
  ('garlic', '/ˈɡɑːlɪk/', 'bawang putih', 'Garlic adds flavor.', 'noun', ARRAY['food', 'spice']::text[], 2),
  ('chili', '/ˈtʃɪli/', 'cabai', 'Spicy red chili.', 'noun', ARRAY['food', 'spice']::text[], 1),
  ('mushroom', '/ˈmʌʃruːm/', 'jamur', 'Mushroom soup is creamy.', 'noun', ARRAY['food', 'vegetable']::text[], 2),
  ('bean', '/biːn/', 'kacang panjang', 'Green beans are crunchy.', 'noun', ARRAY['food', 'vegetable']::text[], 2),
  ('peanut', '/ˈpiːnʌt/', 'kacang tanah', 'Roasted peanuts are crunchy.', 'noun', ARRAY['food', 'legume']::text[], 1),
  ('soy sauce', '/sɔɪ sɔːs/', 'kecap', 'Add soy sauce for flavor.', 'noun', ARRAY['food', 'condiment']::text[], 2),
  ('chili sauce', '/ˈtʃɪli sɔːs/', 'saus cabai', 'Hot chili sauce burns.', 'noun', ARRAY['food', 'condiment']::text[], 2),
  ('water', '/ˈwɔːtə(r)/', 'air', 'Drink clean water daily.', 'noun', ARRAY['drink']::text[], 1),
  ('mineral water', '/ˈmɪnərəl ˈwɔːtə(r)/', 'air mineral', 'Bottled mineral water.', 'noun', ARRAY['drink']::text[], 1),
  ('milk', '/mɪlk/', 'susu', 'Fresh cow milk.', 'noun', ARRAY['drink', 'dairy']::text[], 1),
  ('tea', '/tiː/', 'teh', 'Hot tea with sugar.', 'noun', ARRAY['drink']::text[], 1),
  ('green tea', '/ɡriːn tiː/', 'teh hijau', 'Healthy green tea.', 'noun', ARRAY['drink']::text[], 2),
  ('coffee', '/ˈkɒfi/', 'kopi', 'Strong black coffee.', 'noun', ARRAY['drink']::text[], 1),
  ('juice', '/dʒuːs/', 'jus', 'Fresh fruit juice.', 'noun', ARRAY['drink']::text[], 1),
  ('orange juice', '/ˈɒrɪndʒ dʒuːs/', 'jus jeruk', 'Freshly squeezed orange juice.', 'noun', ARRAY['drink']::text[], 1),
  ('apple juice', '/ˈæpl dʒuːs/', 'jus apel', 'Sweet apple juice.', 'noun', ARRAY['drink']::text[], 1),
  ('mango juice', '/ˈmæŋɡəʊ dʒuːs/', 'jus mangga', 'Tropical mango juice.', 'noun', ARRAY['drink']::text[], 1),
  ('soda', '/ˈsəʊdə/', 'soda', 'Fizzy soda drink.', 'noun', ARRAY['drink']::text[], 1),
  ('cola', '/ˈkəʊlə/', 'kola', 'Cold cola with ice.', 'noun', ARRAY['drink']::text[], 1),
  ('hot chocolate', '/hɒt ˈtʃɒklət/', 'cokelat panas', 'Creamy hot chocolate.', 'noun', ARRAY['drink']::text[], 1),
  ('lemonade', '/ˌleməˈneɪd/', 'limun', 'Fresh lemonade is sour.', 'noun', ARRAY['drink']::text[], 2),
  ('coconut water', '/ˈkəʊkənʌt ˈwɔːtə(r)/', 'air kelapa', 'Natural coconut water.', 'noun', ARRAY['drink']::text[], 2),
  ('energy drink', '/ˈenədʒi drɪŋk/', 'minuman energi', 'Energy drink boosts power.', 'noun', ARRAY['drink']::text[], 2),
  ('milkshake', '/ˈmɪlkʃeɪk/', 'susu kocok', 'Thick chocolate milkshake.', 'noun', ARRAY['drink']::text[], 2),
  ('iced tea', '/aɪst tiː/', 'es teh', 'Cold iced tea refreshes.', 'noun', ARRAY['drink']::text[], 1),
  ('iced coffee', '/aɪst ˈkɒfi/', 'es kopi', 'Iced coffee with cream.', 'noun', ARRAY['drink']::text[], 1),
  ('yogurt drink', '/ˈjɒɡət drɪŋk/', 'minuman yogurt', 'Probiotic yogurt drink.', 'noun', ARRAY['drink']::text[], 2)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- G. ANIMALS (50 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'animals') t
CROSS JOIN (VALUES
  ('cat', '/kæt/', 'kucing', 'My cat is very cute.', 'noun', ARRAY['pet', 'mammal']::text[], 1),
  ('dog', '/dɒɡ/', 'anjing', 'The dog barks loudly.', 'noun', ARRAY['pet', 'mammal']::text[], 1),
  ('bird', '/bɜːd/', 'burung', 'Birds can fly in the sky.', 'noun', ARRAY['wild', 'bird']::text[], 1),
  ('fish', '/fɪʃ/', 'ikan', 'Fish swim in the water.', 'noun', ARRAY['aquatic']::text[], 1),
  ('cow', '/kaʊ/', 'sapi', 'Cows give us milk.', 'noun', ARRAY['farm', 'mammal']::text[], 1),
  ('goat', '/ɡəʊt/', 'kambing', 'The goat eats grass.', 'noun', ARRAY['farm', 'mammal']::text[], 1),
  ('horse', '/hɔːs/', 'kuda', 'Horses run very fast.', 'noun', ARRAY['farm', 'mammal']::text[], 1),
  ('sheep', '/ʃiːp/', 'domba', 'Sheep have soft wool.', 'noun', ARRAY['farm', 'mammal']::text[], 1),
  ('chicken', '/ˈtʃɪkɪn/', 'ayam', 'Chickens lay eggs.', 'noun', ARRAY['farm', 'bird']::text[], 1),
  ('duck', '/dʌk/', 'bebek', 'Ducks swim in the pond.', 'noun', ARRAY['farm', 'bird']::text[], 1),
  ('rabbit', '/ˈræbɪt/', 'kelinci', 'Rabbits have long ears.', 'noun', ARRAY['pet', 'mammal']::text[], 1),
  ('monkey', '/ˈmʌŋki/', 'monyet', 'Monkeys climb trees.', 'noun', ARRAY['wild', 'mammal']::text[], 1),
  ('elephant', '/ˈelɪfənt/', 'gajah', 'Elephants are very big.', 'noun', ARRAY['wild', 'mammal']::text[], 1),
  ('tiger', '/ˈtaɪɡə(r)/', 'harimau', 'Tigers are dangerous animals.', 'noun', ARRAY['wild', 'mammal']::text[], 1),
  ('lion', '/ˈlaɪən/', 'singa', 'The lion is king of the jungle.', 'noun', ARRAY['wild', 'mammal']::text[], 1),
  ('bear', '/beə(r)/', 'beruang', 'Bears love honey.', 'noun', ARRAY['wild', 'mammal']::text[], 1),
  ('snake', '/sneɪk/', 'ular', 'Some snakes are poisonous.', 'noun', ARRAY['wild', 'reptile']::text[], 1),
  ('frog', '/frɒɡ/', 'katak', 'Frogs can jump high.', 'noun', ARRAY['wild', 'amphibian']::text[], 1),
  ('butterfly', '/ˈbʌtəflaɪ/', 'kupu-kupu', 'Butterflies have colorful wings.', 'noun', ARRAY['wild', 'insect']::text[], 1),
  ('bee', '/biː/', 'lebah', 'Bees make honey.', 'noun', ARRAY['wild', 'insect']::text[], 1),
  ('ant', '/ænt/', 'semut', 'Ants are very small.', 'noun', ARRAY['wild', 'insect']::text[], 1),
  ('crocodile', '/ˈkrɒkədaɪl/', 'buaya', 'Crocodiles live in rivers.', 'noun', ARRAY['wild', 'reptile']::text[], 2),
  ('whale', '/weɪl/', 'paus', 'Whales are the biggest mammals.', 'noun', ARRAY['aquatic', 'mammal']::text[], 2),
  ('shark', '/ʃɑːk/', 'hiu', 'Sharks have sharp teeth.', 'noun', ARRAY['aquatic', 'fish']::text[], 2),
  ('dolphin', '/ˈdɒlfɪn/', 'lumba-lumba', 'Dolphins are very smart.', 'noun', ARRAY['aquatic', 'mammal']::text[], 2),
  ('eagle', '/ˈiːɡl/', 'elang', 'Eagles fly very high.', 'noun', ARRAY['wild', 'bird']::text[], 2),
  ('owl', '/aʊl/', 'burung hantu', 'Owls hunt at night.', 'noun', ARRAY['wild', 'bird']::text[], 2),
  ('parrot', '/ˈpærət/', 'burung beo', 'Parrots can talk.', 'noun', ARRAY['pet', 'bird']::text[], 2),
  ('pigeon', '/ˈpɪdʒɪn/', 'merpati', 'Pigeons live in the city.', 'noun', ARRAY['wild', 'bird']::text[], 2),
  ('bat', '/bæt/', 'kelelawar', 'Bats sleep upside down.', 'noun', ARRAY['wild', 'mammal']::text[], 2),
  ('camel', '/ˈkæməl/', 'unta', 'Camels live in the desert.', 'noun', ARRAY['wild', 'mammal']::text[], 2),
  ('fox', '/fɒks/', 'rubah', 'Foxes are very clever.', 'noun', ARRAY['wild', 'mammal']::text[], 2),
  ('wolf', '/wʊlf/', 'serigala', 'Wolves hunt in packs.', 'noun', ARRAY['wild', 'mammal']::text[], 2),
  ('deer', '/dɪə(r)/', 'rusa', 'Deer have beautiful antlers.', 'noun', ARRAY['wild', 'mammal']::text[], 2),
  ('squirrel', '/ˈskwɪrəl/', 'tupai', 'Squirrels collect nuts.', 'noun', ARRAY['wild', 'mammal']::text[], 2),
  ('kangaroo', '/ˌkæŋɡəˈruː/', 'kanguru', 'Kangaroos jump very high.', 'noun', ARRAY['wild', 'mammal']::text[], 2),
  ('panda', '/ˈpændə/', 'panda', 'Pandas eat bamboo.', 'noun', ARRAY['wild', 'mammal']::text[], 2),
  ('koala', '/kəʊˈɑːlə/', 'koala', 'Koalas sleep a lot.', 'noun', ARRAY['wild', 'mammal']::text[], 2),
  ('penguin', '/ˈpeŋɡwɪn/', 'pinguin', 'Penguins cannot fly.', 'noun', ARRAY['wild', 'bird']::text[], 2),
  ('seal', '/siːl/', 'anjing laut', 'Seals are excellent swimmers.', 'noun', ARRAY['aquatic', 'mammal']::text[], 2),
  ('tortoise', '/ˈtɔːtəs/', 'kura-kura darat', 'Tortoises live on land.', 'noun', ARRAY['wild', 'reptile']::text[], 2),
  ('turtle', '/ˈtɜːtl/', 'kura-kura air', 'Turtles live in water.', 'noun', ARRAY['aquatic', 'reptile']::text[], 2),
  ('crab', '/kræb/', 'kepiting', 'Crabs walk sideways.', 'noun', ARRAY['aquatic']::text[], 2),
  ('lobster', '/ˈlɒbstə(r)/', 'lobster', 'Lobsters have big claws.', 'noun', ARRAY['aquatic']::text[], 3),
  ('octopus', '/ˈɒktəpəs/', 'gurita', 'Octopuses have eight arms.', 'noun', ARRAY['aquatic']::text[], 2),
  ('starfish', '/ˈstɑːfɪʃ/', 'bintang laut', 'Starfish live in the ocean.', 'noun', ARRAY['aquatic']::text[], 2),
  ('jellyfish', '/ˈdʒelifɪʃ/', 'ubur-ubur', 'Jellyfish can sting.', 'noun', ARRAY['aquatic']::text[], 2),
  ('mosquito', '/məˈskiːtəʊ/', 'nyamuk', 'Mosquitoes bite and suck blood.', 'noun', ARRAY['insect']::text[], 1),
  ('cockroach', '/ˈkɒkrəʊtʃ/', 'kecoa', 'Cockroaches are dirty insects.', 'noun', ARRAY['insect']::text[], 2),
  ('giraffe', '/dʒəˈrɑːf/', 'jerapah', 'Giraffes have long necks.', 'noun', ARRAY['wild', 'mammal']::text[], 2)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- H. PLACES (50 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'places') t
CROSS JOIN (VALUES
  ('house', '/haʊs/', 'rumah', 'My house is big.', 'noun', ARRAY['building', 'home']::text[], 1),
  ('bedroom', '/ˈbedruːm/', 'kamar tidur', 'I sleep in my bedroom.', 'noun', ARRAY['room']::text[], 1),
  ('bathroom', '/ˈbɑːθruːm/', 'kamar mandi', 'The bathroom is clean.', 'noun', ARRAY['room']::text[], 1),
  ('kitchen', '/ˈkɪtʃɪn/', 'dapur', 'Mom cooks in the kitchen.', 'noun', ARRAY['room']::text[], 1),
  ('living room', '/ˈlɪvɪŋ ruːm/', 'ruang tamu', 'We watch TV in the living room.', 'noun', ARRAY['room']::text[], 1),
  ('yard', '/jɑːd/', 'halaman', 'Children play in the yard.', 'noun', ARRAY['outdoor']::text[], 1),
  ('garden', '/ˈɡɑːdn/', 'kebun', 'Flowers grow in the garden.', 'noun', ARRAY['outdoor']::text[], 1),
  ('balcony', '/ˈbælkəni/', 'balkon', 'I sit on the balcony.', 'noun', ARRAY['outdoor']::text[], 2),
  ('garage', '/ˈɡærɑːʒ/', 'garasi', 'The car is in the garage.', 'noun', ARRAY['building']::text[], 2),
  ('school', '/skuːl/', 'sekolah', 'I go to school every day.', 'noun', ARRAY['building', 'education']::text[], 1),
  ('classroom', '/ˈklɑːsruːm/', 'kelas', 'We study in the classroom.', 'noun', ARRAY['room', 'education']::text[], 1),
  ('library', '/ˈlaɪbrəri/', 'perpustakaan', 'I read books in the library.', 'noun', ARRAY['building', 'education']::text[], 1),
  ('canteen', '/kænˈtiːn/', 'kantin', 'We eat in the canteen.', 'noun', ARRAY['room']::text[], 1),
  ('hospital', '/ˈhɒspɪtl/', 'rumah sakit', 'Sick people go to the hospital.', 'noun', ARRAY['building', 'health']::text[], 1),
  ('police station', '/pəˈliːs ˈsteɪʃn/', 'kantor polisi', 'Police work at the police station.', 'noun', ARRAY['building', 'public']::text[], 2),
  ('post office', '/pəʊst ˈɒfɪs/', 'kantor pos', 'Send letters at the post office.', 'noun', ARRAY['building', 'public']::text[], 2),
  ('bank', '/bæŋk/', 'bank', 'I save money in the bank.', 'noun', ARRAY['building', 'finance']::text[], 1),
  ('supermarket', '/ˈsuːpəmɑːkɪt/', 'supermarket', 'Buy groceries at the supermarket.', 'noun', ARRAY['building', 'shopping']::text[], 1),
  ('market', '/ˈmɑːkɪt/', 'pasar', 'Fresh vegetables at the market.', 'noun', ARRAY['place', 'shopping']::text[], 1),
  ('park', '/pɑːk/', 'taman', 'Children play in the park.', 'noun', ARRAY['outdoor', 'public']::text[], 1),
  ('playground', '/ˈpleɪɡraʊnd/', 'tempat bermain', 'Swings are in the playground.', 'noun', ARRAY['outdoor', 'public']::text[], 1),
  ('restaurant', '/ˈrestrɒnt/', 'restoran', 'We eat dinner at the restaurant.', 'noun', ARRAY['building', 'food']::text[], 1),
  ('cafe', '/ˈkæfeɪ/', 'kafe', 'I drink coffee at the cafe.', 'noun', ARRAY['building', 'food']::text[], 1),
  ('cinema', '/ˈsɪnəmə/', 'bioskop', 'Watch movies at the cinema.', 'noun', ARRAY['building', 'entertainment']::text[], 1),
  ('bus station', '/bʌs ˈsteɪʃn/', 'terminal bus', 'Buses depart from the bus station.', 'noun', ARRAY['building', 'transport']::text[], 2),
  ('airport', '/ˈeəpɔːt/', 'bandara', 'Planes land at the airport.', 'noun', ARRAY['building', 'transport']::text[], 2),
  ('harbor', '/ˈhɑːbə(r)/', 'pelabuhan', 'Ships dock at the harbor.', 'noun', ARRAY['place', 'transport']::text[], 2),
  ('beach', '/biːtʃ/', 'pantai', 'I love swimming at the beach.', 'noun', ARRAY['outdoor', 'nature']::text[], 1),
  ('mountain', '/ˈmaʊntən/', 'gunung', 'The mountain is very high.', 'noun', ARRAY['outdoor', 'nature']::text[], 1),
  ('river', '/ˈrɪvə(r)/', 'sungai', 'Fish live in the river.', 'noun', ARRAY['outdoor', 'nature']::text[], 1),
  ('lake', '/leɪk/', 'danau', 'The lake is calm and peaceful.', 'noun', ARRAY['outdoor', 'nature']::text[], 1),
  ('mosque', '/mɒsk/', 'masjid', 'Muslims pray at the mosque.', 'noun', ARRAY['building', 'religion']::text[], 1),
  ('church', '/tʃɜːtʃ/', 'gereja', 'Christians worship at the church.', 'noun', ARRAY['building', 'religion']::text[], 1),
  ('temple', '/ˈtempl/', 'kuil', 'The temple is very beautiful.', 'noun', ARRAY['building', 'religion']::text[], 2),
  ('shop', '/ʃɒp/', 'toko', 'I buy things at the shop.', 'noun', ARRAY['building', 'shopping']::text[], 1),
  ('mall', '/mɔːl/', 'pusat perbelanjaan', 'The mall has many stores.', 'noun', ARRAY['building', 'shopping']::text[], 1),
  ('stadium', '/ˈsteɪdiəm/', 'stadion', 'Watch football at the stadium.', 'noun', ARRAY['building', 'sport']::text[], 2),
  ('zoo', '/zuː/', 'kebun binatang', 'See animals at the zoo.', 'noun', ARRAY['place', 'entertainment']::text[], 1),
  ('museum', '/mjuˈziːəm/', 'museum', 'Learn history at the museum.', 'noun', ARRAY['building', 'culture']::text[], 2),
  ('hotel', '/həʊˈtel/', 'hotel', 'Tourists stay at the hotel.', 'noun', ARRAY['building', 'accommodation']::text[], 1),
  ('office', '/ˈɒfɪs/', 'kantor', 'Dad works in the office.', 'noun', ARRAY['building', 'work']::text[], 1),
  ('farm', '/fɑːm/', 'peternakan', 'Animals live on the farm.', 'noun', ARRAY['place', 'rural']::text[], 1),
  ('factory', '/ˈfæktri/', 'pabrik', 'Products are made in the factory.', 'noun', ARRAY['building', 'industry']::text[], 2),
  ('theater', '/ˈθɪətə(r)/', 'teater', 'Watch plays at the theater.', 'noun', ARRAY['building', 'entertainment']::text[], 2),
  ('swimming pool', '/ˈswɪmɪŋ puːl/', 'kolam renang', 'I swim in the swimming pool.', 'noun', ARRAY['place', 'sport']::text[], 1),
  ('road', '/rəʊd/', 'jalan', 'Cars drive on the road.', 'noun', ARRAY['outdoor', 'transport']::text[], 1),
  ('bridge', '/brɪdʒ/', 'jembatan', 'The bridge crosses the river.', 'noun', ARRAY['structure', 'transport']::text[], 1),
  ('island', '/ˈaɪlənd/', 'pulau', 'The island is surrounded by water.', 'noun', ARRAY['nature', 'geography']::text[], 2),
  ('desert', '/ˈdezət/', 'gurun', 'The desert is very hot and dry.', 'noun', ARRAY['nature', 'geography']::text[], 2),
  ('village', '/ˈvɪlɪdʒ/', 'desa', 'Life in the village is peaceful.', 'noun', ARRAY['place', 'rural']::text[], 1)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- I. ADJECTIVES (50 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'adjectives') t
CROSS JOIN (VALUES
  ('big', '/bɪɡ/', 'besar', 'The elephant is very big.', 'adjective', ARRAY['size']::text[], 1),
  ('small', '/smɔːl/', 'kecil', 'The ant is very small.', 'adjective', ARRAY['size']::text[], 1),
  ('long', '/lɒŋ/', 'panjang', 'The snake is long.', 'adjective', ARRAY['size']::text[], 1),
  ('short', '/ʃɔːt/', 'pendek', 'The pencil is short.', 'adjective', ARRAY['size']::text[], 1),
  ('tall', '/tɔːl/', 'tinggi', 'The giraffe is tall.', 'adjective', ARRAY['size']::text[], 1),
  ('fat', '/fæt/', 'gemuk', 'The pig is fat.', 'adjective', ARRAY['size']::text[], 1),
  ('thin', '/θɪn/', 'kurus', 'The model is thin.', 'adjective', ARRAY['size']::text[], 1),
  ('old', '/əʊld/', 'tua', 'My grandfather is old.', 'adjective', ARRAY['age']::text[], 1),
  ('young', '/jʌŋ/', 'muda', 'The baby is young.', 'adjective', ARRAY['age']::text[], 1),
  ('new', '/njuː/', 'baru', 'I bought a new car.', 'adjective', ARRAY['age']::text[], 1),
  ('good', '/ɡʊd/', 'baik', 'She is a good student.', 'adjective', ARRAY['quality']::text[], 1),
  ('bad', '/bæd/', 'buruk', 'Smoking is bad for health.', 'adjective', ARRAY['quality']::text[], 1),
  ('happy', '/ˈhæpi/', 'senang', 'I am happy today.', 'adjective', ARRAY['emotion']::text[], 1),
  ('sad', '/sæd/', 'sedih', 'She feels sad.', 'adjective', ARRAY['emotion']::text[], 1),
  ('beautiful', '/ˈbjuːtɪfl/', 'cantik', 'The flower is beautiful.', 'adjective', ARRAY['appearance']::text[], 1),
  ('ugly', '/ˈʌɡli/', 'jelek', 'The monster is ugly.', 'adjective', ARRAY['appearance']::text[], 1),
  ('hot', '/hɒt/', 'panas', 'The sun is hot.', 'adjective', ARRAY['temperature']::text[], 1),
  ('cold', '/kəʊld/', 'dingin', 'Ice is very cold.', 'adjective', ARRAY['temperature']::text[], 1),
  ('clean', '/kliːn/', 'bersih', 'The room is clean.', 'adjective', ARRAY['condition']::text[], 1),
  ('dirty', '/ˈdɜːti/', 'kotor', 'My shoes are dirty.', 'adjective', ARRAY['condition']::text[], 1),
  ('smart', '/smɑːt/', 'pintar', 'He is a smart boy.', 'adjective', ARRAY['intelligence']::text[], 1),
  ('lazy', '/ˈleɪzi/', 'malas', 'Do not be lazy.', 'adjective', ARRAY['character']::text[], 1),
  ('rich', '/rɪtʃ/', 'kaya', 'The businessman is rich.', 'adjective', ARRAY['wealth']::text[], 2),
  ('poor', '/pɔː(r)/', 'miskin', 'They are poor people.', 'adjective', ARRAY['wealth']::text[], 2),
  ('noisy', '/ˈnɔɪzi/', 'berisik', 'The market is noisy.', 'adjective', ARRAY['sound']::text[], 2),
  ('quiet', '/ˈkwaɪət/', 'tenang', 'The library is quiet.', 'adjective', ARRAY['sound']::text[], 1),
  ('fast', '/fɑːst/', 'cepat', 'The car is very fast.', 'adjective', ARRAY['speed']::text[], 1),
  ('slow', '/sləʊ/', 'lambat', 'The turtle is slow.', 'adjective', ARRAY['speed']::text[], 1),
  ('strong', '/strɒŋ/', 'kuat', 'The man is strong.', 'adjective', ARRAY['strength']::text[], 1),
  ('weak', '/wiːk/', 'lemah', 'I feel weak today.', 'adjective', ARRAY['strength']::text[], 1),
  ('kind', '/kaɪnd/', 'baik hati', 'She is very kind.', 'adjective', ARRAY['character']::text[], 1),
  ('cruel', '/ˈkruːəl/', 'kejam', 'The villain is cruel.', 'adjective', ARRAY['character']::text[], 2),
  ('brave', '/breɪv/', 'berani', 'Soldiers are brave.', 'adjective', ARRAY['character']::text[], 2),
  ('shy', '/ʃaɪ/', 'pemalu', 'The boy is shy.', 'adjective', ARRAY['character']::text[], 1),
  ('clever', '/ˈklevə(r)/', 'cerdas', 'She is very clever.', 'adjective', ARRAY['intelligence']::text[], 2),
  ('foolish', '/ˈfuːlɪʃ/', 'bodoh', 'That was a foolish mistake.', 'adjective', ARRAY['intelligence']::text[], 2),
  ('friendly', '/ˈfrendli/', 'ramah', 'Our neighbors are friendly.', 'adjective', ARRAY['character']::text[], 1),
  ('unfriendly', '/ʌnˈfrendli/', 'tidak ramah', 'He seems unfriendly.', 'adjective', ARRAY['character']::text[], 2),
  ('generous', '/ˈdʒenərəs/', 'dermawan', 'She is generous with her time.', 'adjective', ARRAY['character']::text[], 3),
  ('selfish', '/ˈselfɪʃ/', 'egois', 'Do not be selfish.', 'adjective', ARRAY['character']::text[], 2),
  ('polite', '/pəˈlaɪt/', 'sopan', 'Always be polite.', 'adjective', ARRAY['manner']::text[], 2),
  ('rude', '/ruːd/', 'kasar', 'Rude behavior is not acceptable.', 'adjective', ARRAY['manner']::text[], 2),
  ('lucky', '/ˈlʌki/', 'beruntung', 'I am very lucky today.', 'adjective', ARRAY['fortune']::text[], 2),
  ('unlucky', '/ʌnˈlʌki/', 'sial', 'He had an unlucky day.', 'adjective', ARRAY['fortune']::text[], 2),
  ('hard', '/hɑːd/', 'keras', 'The rock is hard.', 'adjective', ARRAY['texture']::text[], 1),
  ('soft', '/sɒft/', 'lembut', 'The pillow is soft.', 'adjective', ARRAY['texture']::text[], 1),
  ('sharp', '/ʃɑːp/', 'tajam', 'The knife is sharp.', 'adjective', ARRAY['quality']::text[], 2),
  ('blunt', '/blʌnt/', 'tumpul', 'The pencil is blunt.', 'adjective', ARRAY['quality']::text[], 3),
  ('expensive', '/ɪkˈspensɪv/', 'mahal', 'The car is expensive.', 'adjective', ARRAY['price']::text[], 2),
  ('cheap', '/tʃiːp/', 'murah', 'The book is cheap.', 'adjective', ARRAY['price']::text[], 1)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;

-- J. COMMON EXPRESSIONS (50 words)
INSERT INTO vocabulary (topic_id, word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
SELECT t.id, v.* FROM (SELECT id FROM topics WHERE slug = 'common-expressions') t
CROSS JOIN (VALUES
  ('Good morning', '/ɡʊd ˈmɔːnɪŋ/', 'selamat pagi', 'Good morning everyone!', 'phrase', ARRAY['greeting']::text[], 1),
  ('Good afternoon', '/ɡʊd ˌɑːftəˈnuːn/', 'selamat siang', 'Good afternoon sir.', 'phrase', ARRAY['greeting']::text[], 1),
  ('Good evening', '/ɡʊd ˈiːvnɪŋ/', 'selamat malam', 'Good evening ladies and gentlemen.', 'phrase', ARRAY['greeting']::text[], 1),
  ('Good night', '/ɡʊd naɪt/', 'selamat tidur', 'Good night, sleep well.', 'phrase', ARRAY['greeting']::text[], 1),
  ('How are you', '/haʊ ɑː juː/', 'apa kabar', 'How are you doing?', 'phrase', ARRAY['question']::text[], 1),
  ('I am fine thank you', '/aɪ æm faɪn θæŋk juː/', 'saya baik terima kasih', 'I am fine thank you.', 'phrase', ARRAY['response']::text[], 1),
  ('See you', '/siː juː/', 'sampai jumpa', 'See you later!', 'phrase', ARRAY['farewell']::text[], 1),
  ('See you tomorrow', '/siː juː təˈmɒrəʊ/', 'sampai besok', 'See you tomorrow at school.', 'phrase', ARRAY['farewell']::text[], 1),
  ('Excuse me', '/ɪkˈskjuːz miː/', 'permisi', 'Excuse me, may I pass?', 'phrase', ARRAY['polite']::text[], 1),
  ('I am sorry', '/aɪ æm ˈsɒri/', 'maaf', 'I am sorry for the mistake.', 'phrase', ARRAY['apology']::text[], 1),
  ('Thank you', '/θæŋk juː/', 'terima kasih', 'Thank you very much!', 'phrase', ARRAY['gratitude']::text[], 1),
  ('You are welcome', '/juː ɑː ˈwelkəm/', 'sama-sama', 'You are welcome!', 'phrase', ARRAY['response']::text[], 1),
  ('What is your name', '/wɒt ɪz jɔː neɪm/', 'siapa namamu', 'What is your name please?', 'phrase', ARRAY['question']::text[], 1),
  ('My name is', '/maɪ neɪm ɪz/', 'nama saya', 'My name is John.', 'phrase', ARRAY['introduction']::text[], 1),
  ('Nice to meet you', '/naɪs tuː miːt juː/', 'senang bertemu denganmu', 'Nice to meet you too.', 'phrase', ARRAY['greeting']::text[], 1),
  ('Where are you from', '/weə(r) ɑː juː frɒm/', 'dari mana asalmu', 'Where are you from originally?', 'phrase', ARRAY['question']::text[], 1),
  ('I do not understand', '/aɪ duː nɒt ˌʌndəˈstænd/', 'saya tidak mengerti', 'I do not understand this.', 'phrase', ARRAY['expression']::text[], 1),
  ('Can you help me', '/kæn juː help miː/', 'bisa tolong saya', 'Can you help me please?', 'phrase', ARRAY['request']::text[], 1),
  ('Please wait', '/pliːz weɪt/', 'tolong tunggu', 'Please wait a moment.', 'phrase', ARRAY['request']::text[], 1),
  ('Do not worry', '/duː nɒt ˈwʌri/', 'jangan khawatir', 'Do not worry about it.', 'phrase', ARRAY['reassurance']::text[], 1),
  ('That is right', '/ðæt ɪz raɪt/', 'itu benar', 'Yes that is right.', 'phrase', ARRAY['confirmation']::text[], 1),
  ('That is wrong', '/ðæt ɪz rɒŋ/', 'itu salah', 'No that is wrong.', 'phrase', ARRAY['correction']::text[], 1),
  ('Be careful', '/biː ˈkeəfl/', 'hati-hati', 'Be careful on the road.', 'phrase', ARRAY['warning']::text[], 1),
  ('Good luck', '/ɡʊd lʌk/', 'semoga beruntung', 'Good luck with your exam!', 'phrase', ARRAY['wish']::text[], 1),
  ('Congratulations', '/kənˌɡrætʃuˈleɪʃnz/', 'selamat', 'Congratulations on your success!', 'phrase', ARRAY['celebration']::text[], 2),
  ('Take care', '/teɪk keə(r)/', 'jaga diri', 'Take care of yourself.', 'phrase', ARRAY['farewell']::text[], 1),
  ('What time is it', '/wɒt taɪm ɪz ɪt/', 'jam berapa sekarang', 'What time is it now?', 'phrase', ARRAY['question']::text[], 1),
  ('I do not know', '/aɪ duː nɒt nəʊ/', 'saya tidak tahu', 'I do not know the answer.', 'phrase', ARRAY['response']::text[], 1),
  ('I think so', '/aɪ θɪŋk səʊ/', 'saya pikir begitu', 'Yes I think so too.', 'phrase', ARRAY['opinion']::text[], 1),
  ('I do not think so', '/aɪ duː nɒt θɪŋk səʊ/', 'saya rasa tidak', 'I do not think so.', 'phrase', ARRAY['opinion']::text[], 2),
  ('Maybe', '/ˈmeɪbi/', 'mungkin', 'Maybe we can go tomorrow.', 'adverb', ARRAY['possibility']::text[], 1),
  ('Of course', '/əv kɔːs/', 'tentu saja', 'Of course I will help you.', 'phrase', ARRAY['agreement']::text[], 1),
  ('Never mind', '/ˈnevə(r) maɪnd/', 'tidak apa-apa', 'Never mind about that.', 'phrase', ARRAY['reassurance']::text[], 1),
  ('Really', '/ˈrɪəli/', 'sungguh', 'Really? That is amazing!', 'adverb', ARRAY['surprise']::text[], 1),
  ('That is interesting', '/ðæt ɪz ˈɪntrəstɪŋ/', 'itu menarik', 'That is very interesting!', 'phrase', ARRAY['opinion']::text[], 1),
  ('I am hungry', '/aɪ æm ˈhʌŋɡri/', 'saya lapar', 'I am hungry now.', 'phrase', ARRAY['feeling']::text[], 1),
  ('I am thirsty', '/aɪ æm ˈθɜːsti/', 'saya haus', 'I am very thirsty.', 'phrase', ARRAY['feeling']::text[], 1),
  ('I am tired', '/aɪ æm ˈtaɪəd/', 'saya lelah', 'I am so tired today.', 'phrase', ARRAY['feeling']::text[], 1),
  ('I am sick', '/aɪ æm sɪk/', 'saya sakit', 'I am feeling sick.', 'phrase', ARRAY['feeling']::text[], 1),
  ('Let us go', '/let ʌs ɡəʊ/', 'ayo pergi', 'Let us go now!', 'phrase', ARRAY['suggestion']::text[], 1),
  ('Wait a minute', '/weɪt ə ˈmɪnɪt/', 'tunggu sebentar', 'Wait a minute please.', 'phrase', ARRAY['request']::text[], 1),
  ('Hurry up', '/ˈhʌri ʌp/', 'cepatlah', 'Hurry up we are late!', 'phrase', ARRAY['command']::text[], 1),
  ('Come here', '/kʌm hɪə(r)/', 'kemari', 'Please come here.', 'phrase', ARRAY['command']::text[], 1),
  ('Go away', '/ɡəʊ əˈweɪ/', 'pergi sana', 'Go away right now!', 'phrase', ARRAY['command']::text[], 1),
  ('Sit down', '/sɪt daʊn/', 'duduklah', 'Please sit down.', 'phrase', ARRAY['command']::text[], 1),
  ('Stand up', '/stænd ʌp/', 'berdirilah', 'Everyone stand up please.', 'phrase', ARRAY['command']::text[], 1),
  ('Open the door', '/ˈəʊpən ðə dɔː(r)/', 'buka pintu', 'Please open the door.', 'phrase', ARRAY['command']::text[], 1),
  ('Close the window', '/kləʊz ðə ˈwɪndəʊ/', 'tutup jendela', 'Close the window please.', 'phrase', ARRAY['command']::text[], 1),
  ('Turn on the light', '/tɜːn ɒn ðə laɪt/', 'nyalakan lampu', 'Turn on the light please.', 'phrase', ARRAY['command']::text[], 1),
  ('Turn off the TV', '/tɜːn ɒf ðə ˌtiː ˈviː/', 'matikan TV', 'Turn off the TV now.', 'phrase', ARRAY['command']::text[], 1)
) v(word, ipa, meaning_id, example_en, part_of_speech, tags, difficulty_level)
ON CONFLICT (word, topic_id) DO NOTHING;
